# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  ["1", "2", "3"].each do |n|
    config.vm.define "zk_centOS_node#{n}" do |zk_config|
      zk_config.vm.box = "boxcutter/centos66"
      zk_config.vm.network "private_network", :ip => "192.168.13.1#{n}"
      zk_config.vm.provision :shell, :path => "vm-zookeeper.sh", :args => n
    end
  end

end