# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  ["1"].each do |n|
    config.vm.define "kf-broker-#{n}" do |zk_config|
      zk_config.vm.box = "boxcutter/centos66"
      zk_config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
      end  
      zk_config.vm.hostname = "kf-broker-#{n}"
      zk_config.vm.network "private_network", :ip => "192.168.13.1#{n}"
      zk_config.vm.provision :shell, :path => "vm-init.sh", :args => n
      zk_config.vm.provision :shell, :path => "vm-zookeeper.sh", :args => n
      zk_config.vm.provision :shell, :path => "vm-kafka.sh", :args => n
      zk_config.vm.provision :shell, :inline => "start zookeeper", :run => "always"
      zk_config.vm.provision :shell, :inline => "start kafka-1", :run => "always"
	  zk_config.vm.provision :shell, :inline => "start kafka-2", :run => "always"
	  zk_config.vm.provision :shell, :inline => "start kafka-3", :run => "always"
    end
  end

  config.vm.define "kf-manager" do |zk_config|
    zk_config.vm.box = "boxcutter/centos66"
    zk_config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end  
    zk_config.vm.hostname = "kf-manager"
    zk_config.vm.network "private_network", :ip => "192.168.13.16"
    zk_config.vm.provision :shell, :path => "vm-init.sh", :args => 6
  end
  
end